export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET:"SET_SOCKET",
  ADD_MESSAGE:"ADD_MESSAGE",
  SET_MESSAGE_SEARCH :"SET_MESSAGE_SEARCH",
  SET_USER_CONTACTS:"SET_USER_CONTACTS",
  SET_ONLINE_USERS:"SET_ONLINE_USERS",
};
